### ISSUE TITLE
new feature: emit interim results during the tcp throughput run

### ISSUE THREAD

**Issue by O-ring** [orkmellanox/sockperf#140]
Hello everyone,

I think an interesting feature to add to sockperf is to print the interim results while the tcp tp test is running. Now the output is giving us only the summary message rate, packet rate and bandwidth.

sockperf: == version #3.7-no.git == 
sockperf[CLIENT] send on:
[ 0] IP = 127.0.0.1       PORT = 11111 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: Starting test...
sockperf: Test end (interrupted by timer)
sockperf: Test ended
sockperf: Total of 1559669 messages sent in 10.000 sec

sockperf: NOTE: test was performed, using msg-size=32768. For getting maximum throughput consider using --msg-size=1472
sockperf: Summary: Message Rate is 155961 [msg/sec], Packet Rate is about 3587103 [pkt/sec] (23 ip frags / msg)
sockperf: Summary: BandWidth is 4873.781 MBps (38990.250 Mbps)

Thanks in advance

**Comment by igor-ivanov** [comment]
Hello, @O-ring. You can use `-A` option for this

**Comment by O-ring** [comment]
Thanks Igor for the tips.

Marco

**Comment by igor-ivanov** [comment]
@O-ring you can reopen this issue if feel you question was not completed.
