### ISSUE TITLE
sockperf pp tcp mode: can't set --mps under 5000 messages per second

### ISSUE THREAD

**Issue by akk988** [orkmellanox/sockperf#147]
Hello everyone,

I have found a bug with sockperf on RaspberryPi when running a pingpong test in tcp mode.

#### Issue description
sockperf message-per-second caused an error when the value is smaller than 5000 messages per seconds. Testing platform is raspberrypi with raspbian 10 OS.

#### Steps to reproduce the issue

1.  On Raspberrypi, Run sockperf as server 
$sockperf server -p 12000 --tcp

2. Run sockperf as client in ping-pong mode with **mps smaller than 5000**
$sockperf pp -i 127.0.0.1 -p 12000 --time 1 **--mps 5000** --tcp --full-log test.txt

this should reprdduce the problem !

3. Run sockperf as client in ping-pong mode with mps larger than 6000
$sockperf pp -i 127.0.0.1 -p 12000 --time 1 --mps 6000 --tcp --full-log test.txt

this should work !

#### What's the expected result?

- Latency results including avarage latency, total observation and histogram

#### What's the actual result?

-[ 0] IP = 127.0.0.1   PORT = 12000 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: Starting test...
sockperf: ### **ERROR: _seqN > m_maxSequenceNo (errno=0 Success)**

#### Additional details / screenshot

- ![Screenshot]()
-
![bug](https://user-images.githubusercontent.com/47817165/118686403-414edf00-b804-11eb-8fe6-aab0f1e0de48.PNG)

**Comment by igor-ivanov** [comment]
Hello @akk988,
I see that you used sockperf v3.6.
Could you check last master or v3.7 because there were few fixes related results calculation after 3.6 (for example https://github.com/Mellanox/sockperf/commit/9716c760697c9801522ccf2fa88b35b1b8398e5d).

**Comment by akk988** [comment]
> Hello @akk988,
> I see that you used sockperf v3.6.
> Could you check last master or v3.7 because there were few fixes related results calculation after 3.6 (for example [9716c76](https://github.com/Mellanox/sockperf/commit/9716c760697c9801522ccf2fa88b35b1b8398e5d)).

Hello Igor,

thank you for your Feedback. This was the problem. I switched from V3.6 to V3.7 and the problem was solved.

BR
