### ISSUE TITLE
ERROR: _seqN > m_maxSequenceNo in v3.7

### ISSUE THREAD

**Issue by GeekerHua** [orkmellanox/sockperf#154]
Hi when I use sockperf under ARM machine, It tell me sockperf: ERROR: _seqN > m_maxSequenceNo (errno=0 Success)。 I change v3.6 to v3.7 but that not slove my problem。
![image](https://user-images.githubusercontent.com/10725548/138689353-83e6bbae-298a-46de-bef6-204ab7837d60.png)

**Comment by igor-ivanov** [comment]
Hello @GeekerHua , do you see such issue just for `under-load` scenario? Did you try `ping-pong` and `throughput`?

**Comment by GeekerHua** [comment]
> throughput
ping-pong not work, throughput work well
![image](https://user-images.githubusercontent.com/10725548/140017523-d2cdf7e5-6be1-42c2-a7b7-6c19530e0da7.png)

**Comment by igor-ivanov** [comment]
could you provide output for `pp` case too.

**Comment by GeekerHua** [comment]
> could you provide output for `pp` case too.

pp output nothing. It's on the picture.

**Comment by igor-ivanov** [comment]
there is no output for pp case on your screen because it is comment out `##`.

**Comment by igor-ivanov** [comment]
@GeekerHua do you have any update?

**Comment by ghanimf** [comment]
Hi,

It also happens to me on Arm with pp test when using --mps parameter.

### Setup
- Amazon Linux 2 (based on RHEL) on AWS with kernel (4.14.248-189.473.amzn2.aarch64).
- Arm64 (64 CPUs)
- sockperf, version 3.7-11.gita57ffb579002

It works **fine** with:
./sockperf server --ip x.y.z.w --tcp --port 5001 --msg-size 400
./sockperf ping-pong --ip x.y.z.w --tcp --port 5001 --time 30 --msg-size 400 --range 100 --full-rtt

It get to **error** with appending --mps 1000 to the client

[ec2-user@ip-172-31-16-82 sockperf]$ ./sockperf ping-pong --ip x.y.z.w --tcp --port 5001 --time 30 --msg-size 400 --range 100 --full-rtt --mps 1000
sockperf: == version #3.7-11.gita57ffb579002 ==
sockperf[CLIENT] send on:sockperf: using recvfrom() to block on socket(s)

[ 0] IP = X.Y.Z.W  PORT =  5001 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: Starting test...
sockperf: ERROR: _seqN > m_maxSequenceNo (errno=0 Success)

From very fast look, maybe the calc of _maxSequenceNo at bringup() function is related.

**Comment by igor-ivanov** [comment]
We will look at possible reason.

**Comment by igor-ivanov** [comment]
Fix https://github.com/Mellanox/sockperf/pull/187 was included into master
