### ISSUE TITLE
ping-pong on Arm seems does not respect --mps parameter

### ISSUE THREAD

**Issue by ghanimf** [orkmellanox/sockperf#155]
Hi,

### Setup
Amazon Linux 2 (based on RHEL) on AWS with kernel (4.14.248-189.473.amzn2.aarch64).
Arm64 (64 CPUs)
sockperf, version 3.7-11.gita57ffb579002

### Test
Ping-Pong Lantecy with TCP
Server: ./sockperf server --ip x.y.z.w --tcp --port 5001 --msg-size 400

### Without specifiying --mps:
./sockperf ping-pong --ip x.y.z.w. --tcp --port 5001 --time 30 --msg-size 400 --range 100 --full-rtt
I got: 
sockperf: [Valid Duration] RunTime=30.000 sec; SentMessages=962683; ReceivedMessages=962683

### With --mps 90000
./sockperf ping-pong --ip x.y.z.w. --tcp --port 5001 --time 30 --msg-size 400 --range 100 --full-rtt --mps 90000
I got:
sockperf: [Total Run] RunTime=30.000 sec; Warm up time=400 msec; SentMessages=1005098; ReceivedMessages=1005097

So seem --mps didn't affect anything.

**Comment by igor-ivanov** [comment]
You show different values.
[Total Run] line shows actual values during test.
[Valid Duration] line displays values that are used in calculation of final results.
[Total Run] > [Valid Duration]

**Comment by ghanimf** [comment]
Hi,
Sorry for the confusion. Here corrected example of the issue:

### Without specifiying --mps:
**Command:**
./sockperf ping-pong --ip x.y.z.w --tcp --port 5001 --time 30 --msg-size 400 --range 100 --full-rt
**Output:**
sockperf: [Total Run] RunTime=30.000 sec; Warm up time=400 msec; SentMessages=1000442; ReceivedMessages=100044

### With --mps=10000
**Command:**
./sockperf ping-pong --ip x.y.z.w --tcp --port 5001 --time 30 --msg-size 400 --range 100 --full-rtt --mps 10000
**Output:**
sockperf: [Total Run] RunTime=30.000 sec; Warm up time=400 msec; SentMessages=1007175; ReceivedMessages=1007174

How come almost same amount of messages are sent/recieved on both cases above (same setup, same period of time)?
It seems --mps parameter didn't affect anything. I would expect it to reduce the amount of messages sent.

Thanks, --Ghanim

**Comment by igor-ivanov** [comment]
@ghanimf please check if current master with fix as https://github.com/Mellanox/sockperf/pull/187 resolves issue
