### ISSUE TITLE
Need help on Sockperf configuration on Azure Ubuntu instances 

### ISSUE THREAD

**Issue by panneerc** [orkmellanox/sockperf#194]
any have can you please clear documentation on sockperf configuration

**Comment by igor-ivanov** [comment]
Hello, could you clarify your question. There is nothing special for Azure from sockperf side.

**Comment by panneerc** [comment]
Hello @igor-ivanov  

We dont have ant clear step by step documentation for the installation and configuration m

can you please provide the step by step documentation

**Comment by igor-ivanov** [comment]
There are wiki pages as https://github.com/Mellanox/sockperf/wiki with description, commands and examples.

**Comment by panneerc** [comment]
Hello @igor-ivanov 

Please there is nothing available in the wiki , some may have to update with proper information.

Thanks

**Comment by igor-ivanov** [comment]
@panneerc what specific information can not be found in wiki. Thanks.

**Comment by panneerc** [comment]
Hello @igor-ivanov  

We dont any information about configuration part of server and client .

Thanks

**Comment by igor-ivanov** [comment]
Please consider
`$man sockperf` or
https://github.com/Mellanox/sockperf/blob/sockperf_v2/doc/main.dox or
https://docs.nvidia.com/networking/pages/viewpage.action?pageId=43720014 or
https://manpages.ubuntu.com/manpages/jammy/man1/sockperf.1.html or
https://www.systutorials.com/docs/linux/man/3-sockperf/#:~:text=SockPerf%20allows%20the%20user%20to,either%20unidirectonally%20or%20bi%2Ddirectionally.

**Comment by panneerc** [comment]
Hello @igor-ivanov  

thanks a lot for the documentation .i will try and let you know if we are facing any issue :)

Thanks

**Comment by panneerc** [comment]
Hello @igor-ivanov  

Thanks a Lot for a Help I am able to run server and Client .
