### ISSUE TITLE
sockperf server hung on sockperf: [tid1269] using recvfrom() to block on socket(s)

### ISSUE THREAD

**Issue by panneerc** [orkmellanox/sockperf#195]
![image](https://user-images.githubusercontent.com/43799032/180125624-c22872f8-bfa6-487a-b950-fd8239f908fe.png)

**Comment by panneerc** [comment]
can some one please check and help this issue ????

**Comment by igor-ivanov** [comment]
Hello, the issue description does not have details. Please check if you have connectivity issue between server and client.

**Comment by panneerc** [comment]
@igor-ivanov  do you have any clear documentation for sockperf server configuration 

For Now  i have done the below steps ,

Installed Ubuntu 
Installed Sockperf 
try to run the server command  as per  above screenshot  
Its on same stage the command is not completing ..,,,

**Comment by DanielLibenson** [comment]
Hi Panneerc,

From the screenshot above, it looks like a connectivity issue between your server and client.
Please run ping-pong test to verify the connectivity.

For all supported Sockperf commands, please run sockperf with -h option (server side: sockperf server -h)
