### ISSUE TITLE
how to install sockperf onwindows 10 and window 11 machines 

### ISSUE THREAD

**Issue by panneerc** [orkmellanox/sockperf#197]

**Comment by igor-ivanov** [comment]
There is PR https://github.com/Mellanox/sockperf/pull/193 with such possibility. It is planned to be pushed to master branch soon.

**Comment by panneerc** [comment]
Hello @igor-ivanov when do we expect the option for windows , do we a time time for this ?

**Comment by panneerc** [comment]
Hello @igor-ivanov  i have one more questions is there any option we can run sockperf in web application some thinh like sppetest ??

**Comment by igor-ivanov** [comment]
sockperf works as usual client/server application using TCP or UDP protocol w/o specific options for windows. See https://www.mankier.com/3/sockperf

**Comment by panneerc** [comment]
@igor-ivanov  there is no specific option for windows as a clients

**Comment by panneerc** [comment]
Hello @igor-ivanov  okay got it 

we are looking like iperf.exe files for windows installation  ??

**Comment by igor-ivanov** [comment]
@panneerc can it be closed?

**Comment by igor-ivanov** [comment]
windows support is a part of master
