### ISSUE TITLE
TCP testing with -F doesn't work

### ISSUE THREAD

**Issue by sm1ly** [orkmellanox/sockperf#221]
Hello!
I am attempting to test various I/O multiplexing (iomux) types using the TCP protocol.
I have a file containing a list of IP addresses and ports.
My intention is to initiate sockperf with the command sockperf sr --tcp -f list -F select/poll/epoll.
However, I encountered an error message:
"sockperf: --tcp conflicts with -f option."
While trying to understand the purpose of the "type" in the "type:ip:port" format within the file, I've been unable to find clarification.
Could you please explain the meaning of this "type" and how I can effectively test different TCP iomux types?

**Comment by igor-ivanov** [comment]
-f option accepts file in special format as
```
T:1.1.1.0:17000
U:1.1.1.1:18000
```
T - TCP
U -UDP

so `--tcp` is not needed in command line

See man page: https://manpages.debian.org/bullseye/sockperf/sockperf.1.en.html
```

$sockperf server -f conf.file -F e
sockperf: == version #3.5-no.git ==
sockperf: [SERVER] listen on:
[ 0] IP = 5.2.1.3        PORT =  6671 # TCP
[ 1] IP = 5.2.1.3        PORT =  6672 # TCP
[ 2] IP = 5.2.1.3        PORT =  6673 # TCP
[ 3] IP = 5.2.1.3        PORT =  6674 # TCP
[ 4] IP = 5.2.1.3        PORT =  6675 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: [tid 4805] using epoll() to block on socket(s)
Every line in feed file should have following format as

where

[U|T] - UDP or TCP protocol;
address - Internet Protocol (IP) address;
port - Port number;
```
