### ISSUE TITLE
Memory issues 

### ISSUE THREAD

**Issue by clydedcruz** [orkmellanox/sockperf#223]
When running sockperf on an Ubuntu machine with 8GB RAM I see the following if my `-t` is set to 2000.

```
sockperf: test failed because of an exception with the following information:
	std::bad_alloc
sockperf: ERROR: program exits because of an error. (errno=12 Cannot allocate memory)
```

Is there a reccomended hardware config to use for running long lived tests with sockperf ? i.e. for days/ weeks.

**Comment by igor-ivanov** [comment]
There is not common advice for this. sockperf collects information about every packet. Minimal size of unit is 14bytes. So total number of required memory depends on test scenario and network configuration. For example you can send single packet per second in throughput mode as `tp --mps=1` for long test duration successfully.
