### ISSUE TITLE
autogen failed

### ISSUE THREAD

**Issue by lix7721** [orkmellanox/sockperf#66]
$./autogen.sh 
++ pwd
- oldpwd=/tmp/sf
  ++ dirname ./autogen.sh
- topdir=.
- cd .
- CURRENT_VERSION_FILE=./build/current-version
- '[' -d .git ']'
- . ./build/versioning.sh
  +++ cat version
  +++ tr -d '\n'
  ++ VERSION=2.7
  +++ git rev-parse HEAD
  ++ GIT_REF=0903aeafefb8a188ecd6ecb47f744c457880021b
  +++ git describe --long --abbrev=12 --dirty
  ++ x=2.7-45-g0903aeafefb8-dirty
  ++ '[' -n 2.7-45-g0903aeafefb8-dirty ']'
  +++ echo 2.7-45-g0903aeafefb8-dirty
  +++ sed -e s/-g/.git/ -e s/-dirty/.dirty/
  +++ sed 's/.*-//'
  ++ x=45.git0903aeafefb8.dirty
  ++ RELEASE=45.git0903aeafefb8.dirty
- echo 2.7-45.git0903aeafefb8.dirty
- echo 0903aeafefb8a188ecd6ecb47f744c457880021b
- rm -rf autom4te.cache
- mkdir -p config/m4 config/aux
- autoreconf -v --install
  autoreconf: Entering directory `.'
  autoreconf: configure.ac: not using Gettext
  autoreconf: running: aclocal -I config/m4
  autoreconf: configure.ac: tracing
  autoreconf: configure.ac: not using Libtool
  autoreconf: running: /usr/bin/autoconf
  configure.ac:87: error: possibly undefined macro: AC_MSG_ERROR
    If this token and others are legitimate, please use m4_pattern_allow.
    See the Autoconf documentation.
  configure:2835: error: possibly undefined macro: AS_VAR_IF
  autoreconf: /usr/bin/autoconf failed with exit status: 1
- exit 1

perl-5.8.8-32
pkgconfig-0.21-2.1
autoconf-2.59-12.2
m4-1.4.5-3.el5.1.2
libtool-1.5.22-7.1
automake-1.9.6-2.3.1

**Comment by avnerbh** [comment]
thanks for your feedback.  we use autogen.sh successfully and we are not aware of problem with autogen.sh.
try on a clean env
if you think you find a bug than a code patch will be the best thing.
if there is no problem then please close the issue

**Comment by avnerbh** [comment]
I am closing this issue since sockperf seems to be okay and since no response from the author of the issue.
Feel free to re-open.
