### ISSUE TITLE
How to compile sockperf with vma_extra.h?

### ISSUE THREAD

**Issue by datar** [orkmellanox/sockperf#68]
The sockperf came with OFED is not compiled with vma_extra.h.
So How to compile sockperf with vma_extra.h?

**Comment by avnerbh** [comment]
According to libvma’s README.txt:
        The VMA extra socket API is located at: /usr/include/mellanox/vma_extra.h

If you don’t see that, than it is a question for libvma.
Avner

**Comment by OphirMunk** [comment]
What command did you use for OFED installation and what command did you use for VMA installation?
It is best that when installing OFED you add "--vma-eth" flag such that VMA (over Ethernet) is installed as part of OFED installation (see installation options with "--help")

My favorite parameters (when working over Ethernet):
sudo ./mlnxofedinstall --vma-eth --force --force-fw-update

**Comment by OphirMunk** [comment]
Another option for vma_extra.h installation:
Clone latest VMA version:
-> cd "working directory"
-> git clone https://github.com/Mellanox/libvma.git -b master
-> cd libvma
Compile:
->./autogen.sh
-> ./configure
-> make -j
-> sudo make install
That should install vma_extra.h under:
/usr/local/include/mellanox/vma_extra.h

**Comment by datar** [comment]
Thank you @OphirMunk ,
I used --vma parameter to install libvma.
Do I need add --vma-eth option if I work on IPoIB mode?

**Comment by OphirMunk** [comment]
Good choice. --vma options is applicable for both Eth and IB (your case). You did right.
