### ISSUE TITLE
sockperf works with  --vmazcopyread option

### ISSUE THREAD

**Issue by datar** [orkmellanox/sockperf#71]
Hi,
I added this option `--vmazcopyread` to use VMA extra APIs in sockperf test.
Sockperf on client and server shown this message

> sockperf: VMA Extra API found - using VMA's receive zero copy and messages filter APIs

However I got almost same latency result. Sometime the std-dev value got worse. 

Is my option correct? 
Do I need change options in libvma or sockperf to use  --vmazcopyread?

Thank you very much!

**Comment by rosenbaumalex** [comment]
The gain you would expect to see will depend on what the application does with this zero copy buffer VMA provided. 
If I recall correctly, sockperf copies the data into an application buffer, so there is no real expected gain here. You only get to test the feature and view this as an example code.

What msg size are you testing in your ping-pong test command?
For small (<250 Bytes) you will not see much difference. The pointer managing overhead is bigger then the data copy on recvfrom().
For large packet size you should see more improvement with this. Try with UDP 1472 bytes (max size below MTU).

Also, we recommend this --vmazcopyread for receive only test. sockperf server side in ThroughPut (TP) test for large message can demonstrate this.
