### ISSUE TITLE
About message size.

### ISSUE THREAD

**Issue by qinhunter** [orkmellanox/sockperf#87]
I tried sockperf in ping-pong with `-m 65536` and it said 'too big size'.I want to know the maximum size and if I could make it larger like 128*1024 by modifying the code?

**Comment by liranoz12** [comment]
@qinhunter,

The maximum supported message size is  65,506 bytes (we are working to change this to 65,507).
When trying to use a higher value than allowed you will receive the following message :

> sockperf: '-m' Invalid message size: <VALUE> (max: 65506)

Which protocol do you use?
The maximum message size for UDP is 65,507
https://en.wikipedia.org/wiki/User_Datagram_Protocol
> However the actual limit for the data length, which is imposed by the underlying IPv4 protocol, is 65,507 bytes (65,535 − 8 byte UDP header − 20 byte IP header)

TCP is basicly a stream so the payload of each packet can exceed 64k but the acutal size is limited by the MTU.

If you want to increase the maximum message size you need to change [MAX_PAYLOAD_SIZE](https://github.com/Mellanox/sockperf/blob/sockperf_v2/src/Defs.cpp#L59) parameter value.



Liran.
