### ISSUE TITLE
Error compiling the package "MODE_SERVER"

### ISSUE THREAD

**Issue by yurgun** [orkmellanox/sockperf#93]
I downloaded the package and executed ./configure then tried to compile the package 
$make  (also make install) 

then it showed error like this 

> SockPerf.cpp: In function ‘int bringup(const int*)’:
> SockPerf.cpp:3167:54: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
>    if (!s_user_params.b_stream && !s_user_params.mode == MODE_SERVER) {

Thank you.

**Comment by rafiw** [comment]
Hi @yurgun what OS and compiler are you using?
thanks

**Comment by yurgun** [comment]
OS is:
Ubuntu Server 16.04.1 LTS
and the compiler:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by rafiw** [comment]
Hi @yurgun, 
i'm not sure what version\branch you are using looking on latest code in branch [sockperf_v2](https://github.com/Mellanox/sockperf) your code is very different then our [latest release code]( https://github.com/Mellanox/sockperf/blob/sockperf_v2/src/SockPerf.cpp#L3301) (look in the code and code line).
please update your code.
Thanks Rafi
